import streamlit as st

from shared.theme import inject_theme, render_letterhead, render_results, render_disclaimer
from shared.api_client import check_rfp, evaluate_bid, ApiError

st.set_page_config(page_title="Buyer Desk — RFP Sentinel", page_icon="🛡️", layout="centered")
inject_theme()
render_letterhead("Procurement Compliance Desk", role="Buyer")

tab_rfp, tab_bid = st.tabs(["RFP Compliance Check", "Bid Evaluation"])

with tab_rfp:
    st.markdown("#### Draft RFP Norm Check")
    st.caption("Upload a draft RFP. It will be checked against known GeM / procurement norm clauses.")

    rfp_upload = st.file_uploader("RFP Document (PDF)", type=["pdf"], key="rfp_check_upload")

    if st.button("Run Compliance Check", type="primary", disabled=rfp_upload is None):
        with st.spinner("Processing RFP — extracting text, chunking, running compliance checks…"):
            try:
                data = check_rfp(rfp_upload.getvalue(), rfp_upload.name)
                st.success(
                    f"Done. {data['pages_processed']} pages processed, "
                    f"{data['chunks_extracted']} clauses/sections extracted."
                )
                render_results(data["issues"], f"Document: <b>{data['filename']}</b>")
            except ApiError as e:
                st.error(str(e))

with tab_bid:
    st.markdown("#### Bid Response Evaluation")
    st.caption("Upload the RFP and a bidder's response. Each RFP clause is checked for a corresponding response in the bid.")

    col1, col2 = st.columns(2)
    with col1:
        rfp_for_bid = st.file_uploader("RFP Document (PDF)", type=["pdf"], key="bid_rfp_upload")
    with col2:
        bid_upload = st.file_uploader("Bidder Response (PDF)", type=["pdf"], key="bid_upload")

    if st.button("Run Bid Evaluation", type="primary", disabled=(rfp_for_bid is None or bid_upload is None)):
        with st.spinner("Processing RFP and bid — extracting text, matching clauses…"):
            try:
                data = evaluate_bid(
                    rfp_for_bid.getvalue(), rfp_for_bid.name,
                    bid_upload.getvalue(), bid_upload.name,
                )
                st.success(f"Done. {data['clauses_checked']} RFP clauses checked against the bid.")
                render_results(
                    data["issues"],
                    f"RFP: <b>{data['rfp_filename']}</b> vs. Bid: <b>{data['bid_filename']}</b>",
                )
            except ApiError as e:
                st.error(str(e))

render_disclaimer(
    "Note: compliance findings are generated by a rule-based keyword check for this demo, "
    "standing in for the full norm-retrieval agent under development. Treat results as "
    "illustrative, not authoritative."
)
